insert into public.modules (slug, title, summary, sort_order)
values
  ('human-end', 'The Human End', 'Flourishing, purpose, and practical reason in classical ethics.', 1),
  ('habit-and-character', 'Habit and Character', 'How actions form character and why repetition matters.', 2),
  ('practical-wisdom', 'Practical Wisdom', 'Judgment, deliberation, and choosing well in concrete situations.', 3),
  ('virtues-and-vices', 'Virtues and Vices', 'The architecture of the virtues and their corresponding distortions.', 4),
  ('community-and-friendship', 'Community and Friendship', 'Political life, friendship, and shared standards of excellence.', 5)
on conflict (slug) do update
set title = excluded.title,
    summary = excluded.summary,
    sort_order = excluded.sort_order;

with module_refs as (
  select id, slug from public.modules
)
insert into public.lessons
(module_id, slug, title, summary, key_arguments, objections, key_terms, references_text, body_markdown, sort_order)
values
  ((select id from module_refs where slug = 'human-end'), 'why-flourishing', 'Why Flourishing Is the Aim', 'Eudaimonia as activity in accordance with virtue over a complete life.',
   array['The good life is not reducible to feeling good.', 'Human excellence concerns reason-governed action.'],
   array['Can plural societies share one account of flourishing?', 'Is this ideal elitist or exclusionary?'],
   '[{"term":"Eudaimonia","definition":"Flourishing through excellent activity"}]'::jsonb,
   array['Aristotle, Nicomachean Ethics I', 'Anscombe, Modern Moral Philosophy'],
   'Flourishing is not a mood; it is a way of living over time.', 1),
  ((select id from module_refs where slug = 'human-end'), 'function-argument', 'The Function Argument', 'What it means to identify human work and human excellence.',
   array['Functions explain standards of success.', 'Human function concerns rational activity.'],
   array['Does biological function imply normativity?', 'Can modern life reject teleology entirely?'],
   '[{"term":"Ergon","definition":"Characteristic function or work"}]'::jsonb,
   array['Aristotle, Nicomachean Ethics I.7'],
   'The function argument provides a criterion, not a shortcut.', 2),
  ((select id from module_refs where slug = 'human-end'), 'goods-conflict', 'When Goods Conflict', 'How to rank, integrate, and sacrifice goods responsibly.',
   array['Some goods are in tension but still real.', 'Practical wisdom adjudicates without simple formulas.'],
   array['Can ranking goods become rationalization?', 'Do tragedies defeat ethical systems?'],
   '[{"term":"Practical syllogism","definition":"Reasoning from ends to action"}]'::jsonb,
   array['Martha Nussbaum, Fragility of Goodness'],
   'Mature ethics must survive tragic choices.', 3),

  ((select id from module_refs where slug = 'habit-and-character'), 'becoming-just', 'Becoming Just', 'How repeated action forms stable dispositions.',
   array['Character is trained, not inherited ready-made.', 'Practices and institutions shape moral perception.'],
   array['Can people radically change later in life?', 'How much is choice versus conditioning?'],
   '[{"term":"Hexis","definition":"Stable disposition or state of character"}]'::jsonb,
   array['Aristotle, Nicomachean Ethics II'],
   'Habit is moral memory embodied in action.', 1),
  ((select id from module_refs where slug = 'habit-and-character'), 'pleasure-and-pain', 'Pleasure, Pain, and Training', 'Why emotional education matters to moral development.',
   array['Virtue calibrates pleasure and pain.', 'A good education trains affective responses.'],
   array['Is this moral conditioning?', 'Can ascetic ideals distort healthy pleasure?'],
   '[{"term":"Affect","definition":"Pattern of felt response that influences judgment"}]'::jsonb,
   array['Aristotle, Nicomachean Ethics II.3'],
   'The undisciplined heart can sabotage clear reason.', 2),
  ((select id from module_refs where slug = 'habit-and-character'), 'moral-education', 'Moral Education and Institutions', 'Families, schools, and traditions as character-forming contexts.',
   array['No one becomes virtuous in a vacuum.', 'Law and culture can scaffold virtue.'],
   array['When should inherited norms be resisted?', 'Can institutions cultivate vice?'],
   '[{"term":"Paideia","definition":"Formation through cultural education"}]'::jsonb,
   array['Alasdair MacIntyre, After Virtue'],
   'Institutions can teach discipline or corruption.', 3),

  ((select id from module_refs where slug = 'practical-wisdom'), 'deliberation', 'Deliberation and Choice', 'How wise agents deliberate under uncertainty.',
   array['Deliberation concerns means ordered to good ends.', 'Choice reveals character under pressure.'],
   array['Can deliberation be too slow for crisis?', 'What about algorithmic decision aids?'],
   '[{"term":"Phronesis","definition":"Practical wisdom in action"}]'::jsonb,
   array['Aristotle, Nicomachean Ethics VI'],
   'Prudence is not caution; it is lucid action.', 1),
  ((select id from module_refs where slug = 'practical-wisdom'), 'moral-perception', 'Moral Perception', 'Seeing what matters before applying principles.',
   array['Attention is ethically loaded.', 'Experience refines moral salience.'],
   array['Does perception invite bias?', 'Can rules compensate for poor perception?'],
   '[{"term":"Salience","definition":"What stands out as ethically relevant"}]'::jsonb,
   array['Iris Murdoch, The Sovereignty of Good'],
   'Often the first moral task is to notice correctly.', 2),
  ((select id from module_refs where slug = 'practical-wisdom'), 'counsel-and-friends', 'Counsel, Correction, and Friends', 'Why good judgment depends on accountable relationships.',
   array['Private reasoning needs public testing.', 'Friendship can correct self-deception.'],
   array['How do we choose trustworthy counsel?', 'Can dependence weaken autonomy?'],
   '[{"term":"Parrhesia","definition":"Frank speech offered for another’s good"}]'::jsonb,
   array['Aristotle, Nicomachean Ethics IX'],
   'Wisdom matures in dialogue, not isolation.', 3),

  ((select id from module_refs where slug = 'virtues-and-vices'), 'golden-mean', 'The Golden Mean', 'Virtue as fitting response between deficiency and excess.',
   array['The mean is relative to us and context-sensitive.', 'Virtue is precise rather than mediocre.'],
   array['Is the mean too vague to guide action?', 'Some acts appear always wrong.'],
   '[{"term":"Mean","definition":"Fitting measure determined by reason"}]'::jsonb,
   array['Aristotle, Nicomachean Ethics II.6'],
   'The mean is demanding, not moderate for its own sake.', 1),
  ((select id from module_refs where slug = 'virtues-and-vices'), 'catalogue-virtues', 'Mapping Core Virtues', 'How courage, temperance, justice, and prudence interrelate.',
   array['Virtues are mutually reinforcing.', 'Corrupt forms can mimic virtue.'],
   array['Are virtue lists culturally narrow?', 'How should modern professions adapt them?'],
   '[{"term":"Cardinal virtues","definition":"Prudence, justice, temperance, courage"}]'::jsonb,
   array['Plato, Republic IV', 'Aquinas, Summa Theologiae'],
   'No virtue survives long without the others.', 2),
  ((select id from module_refs where slug = 'virtues-and-vices'), 'vice-patterns', 'Vice as Pattern', 'How self-deception stabilizes destructive habits.',
   array['Vice is often coherent and strategic.', 'Naming patterns reduces rationalization.'],
   array['Can moral language become punitive?', 'How does grace alter vice narratives?'],
   '[{"term":"Akrasia","definition":"Weakness of will against better judgment"}]'::jsonb,
   array['Aristotle, Nicomachean Ethics VII'],
   'Vice persists when excuses become identity.', 3),

  ((select id from module_refs where slug = 'community-and-friendship'), 'friendship-types', 'Types of Friendship', 'Utility, pleasure, and friendship of character.',
   array['Deep friendship aims at the good of the other.', 'Friendship shapes moral aspiration.'],
   array['Can unequal friendships remain virtuous?', 'What happens when values diverge?'],
   '[{"term":"Philia","definition":"Civic and personal friendship"}]'::jsonb,
   array['Aristotle, Nicomachean Ethics VIII-IX'],
   'The right friend tells the truth without contempt.', 1),
  ((select id from module_refs where slug = 'community-and-friendship'), 'virtue-and-politics', 'Virtue and Political Life', 'Why institutions matter for the cultivation of citizens.',
   array['Politics concerns shared goods.', 'Law can habituate either virtue or vice.'],
   array['Can liberal neutrality avoid substantive ethics?', 'How do plural societies negotiate virtue claims?'],
   '[{"term":"Common good","definition":"Goods realized only through shared life"}]'::jsonb,
   array['Aristotle, Politics', 'MacIntyre, Dependent Rational Animals'],
   'A private ethic without civic form is fragile.', 2),
  ((select id from module_refs where slug = 'community-and-friendship'), 'tradition-and-critique', 'Tradition and Critique', 'Receiving moral traditions without surrendering critical judgment.',
   array['Traditions are living arguments.', 'Critique can be loyal rather than destructive.'],
   array['When does critique become cynicism?', 'How do we avoid traditionalism?'],
   '[{"term":"Tradition-constituted inquiry","definition":"Reasoning within inherited practices"}]'::jsonb,
   array['Alasdair MacIntyre, Three Rival Versions of Moral Enquiry'],
   'Responsible inheritance requires both gratitude and scrutiny.', 3)
on conflict (module_id, slug) do update
set title = excluded.title,
    summary = excluded.summary,
    key_arguments = excluded.key_arguments,
    objections = excluded.objections,
    key_terms = excluded.key_terms,
    references_text = excluded.references_text,
    body_markdown = excluded.body_markdown,
    sort_order = excluded.sort_order;

insert into public.virtues (slug, name, description, deficiency_label, excess_label, default_order)
values
  ('courage', 'Courage', 'Steadfast action in the face of fear for the sake of the good.', 'Cowardice', 'Rashness', 1),
  ('temperance', 'Temperance', 'Rightly ordered desire and disciplined appetite.', 'Insensibility', 'Self-indulgence', 2),
  ('justice', 'Justice', 'Rendering what is due to others with consistency and fairness.', 'Partiality', 'Legalism', 3),
  ('prudence', 'Prudence', 'Practical wisdom in judging and acting well.', 'Carelessness', 'Cunning', 4),
  ('truthfulness', 'Truthfulness', 'Accurate speech and self-presentation.', 'Self-deprecation', 'Boastfulness', 5),
  ('patience', 'Patience', 'Enduring difficulty without resentment or collapse.', 'Irritability', 'Apathy', 6),
  ('magnanimity', 'Magnanimity', 'Greatness of soul proportionate to real worth.', 'Smallness of soul', 'Vanity', 7),
  ('humility', 'Humility', 'Clear-sighted self-estimation before truth and others.', 'Self-abasement', 'Pride', 8),
  ('fortitude', 'Fortitude', 'Endurance in sustained hardship for worthy ends.', 'Fragility', 'Hardness', 9),
  ('friendliness', 'Friendliness', 'Civility and goodwill in ordinary social life.', 'Quarrelsomeness', 'Obsequiousness', 10),
  ('liberality', 'Liberality', 'Generosity with resources under reason.', 'Stinginess', 'Prodigality', 11),
  ('gentleness', 'Gentleness', 'Right measure of anger under reason.', 'Apathy', 'Irascibility', 12),
  ('industry', 'Industry', 'Steady, disciplined work toward worthy tasks.', 'Sloth', 'Workaholism', 13),
  ('fidelity', 'Fidelity', 'Keeping faith in commitments and relationships.', 'Inconstancy', 'Possessiveness', 14),
  ('gratitude', 'Gratitude', 'Acknowledgment of goods received and their sources.', 'Ingratitude', 'Servility', 15),
  ('frankness', 'Frankness', 'Honest speech directed toward genuine good.', 'Evasion', 'Cruel bluntness', 16)
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    deficiency_label = excluded.deficiency_label,
    excess_label = excluded.excess_label,
    default_order = excluded.default_order;
